all: a3p1Server1 a3p2Server2 a3p3Server3 a3p1Client1 a3p2Client2 a3p3Client3

a3p1Server1: a3p1Server1.c
	gcc -o a3p1Server1 a3p1Server1.c -lpthread

a3p1Client1: a3p1Client1.c
	gcc -o a3p1Client1 a3p1Client1.c -lpthread 
 
a3p2Server2: a3p2Server2.c
	gcc -o a3p2Server2 a3p2Server2.c -lpthread

a3p2Client2: a3p2Client2.c
	gcc -o a3p2Client2 a3p2Client2.c -lpthread

a3p3Server3: a3p3Server3.c
	gcc -o a3p3Server3 a3p3Server3.c -lpthread

a3p3Client3: a3p3Client3.c
	gcc -o a3p3Client3 a3p3Client3.c -lpthread
